### ISSUE TITLE
Camera simulator

### ISSUE THREAD

**Issue by kripper** [chobitsfan/apriltag_plnd#3]
Are you using any camera simulator?
If not, I can provide a simple Python based OpenGL simulator and provide instructions.

**Comment by kripper** [comment]
Released here:
https://github.com/kripper/mavlink-camera-simulator

**Comment by chobitsfan** [comment]
Hi @kripper Thank you very much. It is really helpful.

**Comment by kripper** [comment]
And thanks to you too.
